version: "3.7"
services:

  # nginx container
  proxy:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/wait-for-it.sh:/wait-for-it.sh
      - ./nginx/entrypoint.sh:/entrypoint.sh

  # react container
  client:
    build: ./react
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
  
  # express container
  api:
    build: ./express
    volumes:
      - ./express:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      SESSION_SECRET: foo
      MONGO_USERNAME: root
      MONGO_PASSWORD: password

  # mongo db container on 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
