version: "3.7"
services:

  # prod-like container on http://localhost
  client-prod:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'

  # dev container on http://localhost:3000
  client-dev:
    build: ./react
    ports:
      - '3000:3000'
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
  
  # express container
  api:
    build: ./express
    volumes:
      - ./express:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: password

  # mongo db container
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
