version: "3.7"
services:

  # nginx container
  proxy:
    build: ./nginx
    ports:
      - '80:80'

  # react container
  client:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
  
  # express container
  api:
    build: ./express
    environment:
      NODE_ENV: 'production'
      SESSION_SECRET: foo
      MONGO_USERNAME: root
      MONGO_PASSWORD: password

  # mongo db container on 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
