# Stage 1: Build React Artifact
FROM node AS build-react

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./package.json ./package.json 
RUN npm install --silent
COPY . .
RUN npm run build

# Stage 2: Build Nginx Image
FROM nginx

COPY --from=build-react /usr/src/app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]